const fs = require('fs')
const path = require('path')

const ALL_DESTINATIONS = [
  // Domestic
  {
    _id: 'dest-andaman',
    _type: 'destination',
    name: 'Andaman & Nicobar Islands',
    slug: {_type: 'slug', current: 'andaman'},
    country: 'India',
    region: 'Bay of Bengal',
    shortDescription: 'Turquoise ocean waters, powder white sand beaches, coral reefs, and profound freedom heritage.',
    bestTimeToVisit: 'October to May',
    idealDuration: '5 Days / 4 Nights',
    highlights: ['Radhanagar Beach', 'Cellular Jail Memorial', 'Elephant Beach Snorkeling', 'Makruzz Catamaran'],
  },
  {
    _id: 'dest-kashmir',
    _type: 'destination',
    name: 'Kashmir Valley',
    slug: {_type: 'slug', current: 'kashmir'},
    country: 'India',
    region: 'North India',
    shortDescription: 'Paradise on Earth with snow-capped Pir Panjal peaks, Dal Lake houseboats, and saffron meadows.',
    bestTimeToVisit: 'March to October (Summer & Autumn) / Dec to Feb (Snow & Skiing)',
    idealDuration: '6 Days / 5 Nights',
    highlights: ['Dal Lake Shikara Ride', 'Gulmarg Gondola Cable Car', 'Pahalgam Betaab Valley', 'Mughal Gardens'],
  },
  {
    _id: 'dest-kerala',
    _type: 'destination',
    name: 'Kerala — God\'s Own Country',
    slug: {_type: 'slug', current: 'kerala'},
    country: 'India',
    region: 'South India',
    shortDescription: 'Lush tea plantations in Munnar, tranquil backwater houseboats in Alleppey, and spice plantations.',
    bestTimeToVisit: 'September to March',
    idealDuration: '6 Days / 5 Nights',
    highlights: ['Alleppey Luxury Houseboat', 'Munnar Tea Gardens', 'Thekkady Periyar Wildlife', 'Kochi Fort'],
  },
  {
    _id: 'dest-rajasthan',
    _type: 'destination',
    name: 'Rajasthan & Golden Triangle',
    slug: {_type: 'slug', current: 'rajasthan'},
    country: 'India',
    region: 'North India',
    shortDescription: 'Majestic forts, royal palaces, desert dunes, and timeless architectural grandeur.',
    bestTimeToVisit: 'October to March',
    idealDuration: '6 Days / 5 Nights',
    highlights: ['Taj Mahal in Agra', 'Jaipur Amber Fort & Hawa Mahal', 'Udaipur Lake Palace', 'Jodhpur Mehrangarh'],
  },
  {
    _id: 'dest-goa',
    _type: 'destination',
    name: 'Goa',
    slug: {_type: 'slug', current: 'goa'},
    country: 'India',
    region: 'West Coast India',
    shortDescription: 'Golden sand beaches, private yacht cruises, Portuguese colonial architecture, and vibrant nightlife.',
    bestTimeToVisit: 'November to April',
    idealDuration: '4 Days / 3 Nights',
    highlights: ['Private Mandovi River Yacht', 'South Goa Secluded Beaches', 'Dudhsagar Waterfalls', 'Fort Aguada'],
  },
  {
    _id: 'dest-himachal',
    _type: 'destination',
    name: 'Himachal Pradesh',
    slug: {_type: 'slug', current: 'himachal'},
    country: 'India',
    region: 'North India',
    shortDescription: 'Towering pine forests, alpine rivers, snow adventures at Solang Valley, and colonial Shimla charm.',
    bestTimeToVisit: 'March to June & December to February',
    idealDuration: '6 Days / 5 Nights',
    highlights: ['Solang Valley Snow Sports', 'Atal Tunnel & Sissu', 'Manali Mall Road & Old Manali', 'Shimla Ridge'],
  },
  {
    _id: 'dest-ladakh',
    _type: 'destination',
    name: 'Ladakh',
    slug: {_type: 'slug', current: 'ladakh'},
    country: 'India',
    region: 'Himalayas',
    shortDescription: 'Land of High Passes, high-altitude desert dunes at Nubra, and the shimmering blue Pangong Tso Lake.',
    bestTimeToVisit: 'May to September',
    idealDuration: '7 Days / 6 Nights',
    highlights: ['Pangong Tso Lake Camping', 'Khardung La Pass (17,982 ft)', 'Nubra Valley Camel Safari', 'Magnetic Hill'],
  },
  {
    _id: 'dest-uttarakhand',
    _type: 'destination',
    name: 'Uttarakhand',
    slug: {_type: 'slug', current: 'uttarakhand'},
    country: 'India',
    region: 'North India',
    shortDescription: 'Holy Ganges Ganga Aarti in Rishikesh, Himalayan wellness retreats, and scenic Mussoorie hill views.',
    bestTimeToVisit: 'March to November',
    idealDuration: '6 Days / 5 Nights',
    highlights: ['Rishikesh Ganga Aarti & Rafting', 'Mussoorie Kempty Falls', 'Haridwar Har Ki Pauri', 'Nainital Lake'],
  },
  {
    _id: 'dest-sikkim',
    _type: 'destination',
    name: 'Sikkim & Darjeeling',
    slug: {_type: 'slug', current: 'sikkim'},
    country: 'India',
    region: 'North East India',
    shortDescription: 'Spectacular views of Mt. Kanchenjunga, serene Buddhist monasteries, and aromatic Darjeeling tea hills.',
    bestTimeToVisit: 'March to May & October to December',
    idealDuration: '6 Days / 5 Nights',
    highlights: ['Tsomgo Lake & Nathula Pass', 'Tiger Hill Sunrise', 'Darjeeling Toy Train Heritage', 'Rumtek Monastery'],
  },
  {
    _id: 'dest-udaipur',
    _type: 'destination',
    name: 'Udaipur & Royal Mewar',
    slug: {_type: 'slug', current: 'udaipur'},
    country: 'India',
    region: 'Rajasthan',
    shortDescription: 'The City of Lakes with royal marble palaces, sunset boat rides on Lake Pichola, and heritage hospitality.',
    bestTimeToVisit: 'October to March',
    idealDuration: '5 Days / 4 Nights',
    highlights: ['Lake Pichola Boat Cruise', 'City Palace Complex', 'Saheliyon Ki Bari', 'Jagmandir Island'],
  },

  // International
  {
    _id: 'dest-bali',
    _type: 'destination',
    name: 'Bali, Indonesia',
    slug: {_type: 'slug', current: 'bali'},
    country: 'Indonesia',
    region: 'Southeast Asia',
    shortDescription: 'Tropical island luxury, emerald rice terraces in Ubud, sacred sea temples, and Nusa Penida cliffs.',
    bestTimeToVisit: 'April to October',
    idealDuration: '6 Days / 5 Nights',
    highlights: ['Nusa Penida Kelingking T-Rex Cliff', 'Ubud Tegalalang Rice Terraces', 'Tanah Lot Sunset', 'Mount Batur Sunrise'],
  },
  {
    _id: 'dest-dubai',
    _type: 'destination',
    name: 'Dubai & UAE',
    slug: {_type: 'slug', current: 'dubai'},
    country: 'United Arab Emirates',
    region: 'Middle East',
    shortDescription: 'Ultra-futuristic architectural wonders, Burj Khalifa views, Arabian desert safaris, and luxury marina yachts.',
    bestTimeToVisit: 'November to April',
    idealDuration: '5 Days / 4 Nights',
    highlights: ['Burj Khalifa 124th Floor View', 'Red Dune Desert Safari & BBQ', 'Dubai Marina Luxury Yacht', 'Museum of the Future'],
  },
  {
    _id: 'dest-thailand',
    _type: 'destination',
    name: 'Thailand',
    slug: {_type: 'slug', current: 'thailand'},
    country: 'Thailand',
    region: 'Southeast Asia',
    shortDescription: 'Limestone karsts in Phi Phi Island, vibrant Bangkok street food, golden Buddhist temples, and luxury beach clubs.',
    bestTimeToVisit: 'November to April',
    idealDuration: '6 Days / 5 Nights',
    highlights: ['Phi Phi & Maya Bay Speedboat Tour', 'James Bond Island', 'Bangkok Grand Palace', 'Chao Phraya Dinner Cruise'],
  },
  {
    _id: 'dest-singapore',
    _type: 'destination',
    name: 'Singapore',
    slug: {_type: 'slug', current: 'singapore'},
    country: 'Singapore',
    region: 'Southeast Asia',
    shortDescription: 'The Garden City with Marina Bay Sands, futuristic Supertree Grove, Universal Studios, and world-class culinary trails.',
    bestTimeToVisit: 'All Year Round',
    idealDuration: '5 Days / 4 Nights',
    highlights: ['Gardens by the Bay & Cloud Forest', 'Universal Studios Singapore', 'Night Safari Experience', 'Marina Bay SkyPark'],
  },
  {
    _id: 'dest-maldives',
    _type: 'destination',
    name: 'Maldives',
    slug: {_type: 'slug', current: 'maldives'},
    country: 'Maldives',
    region: 'Indian Ocean',
    shortDescription: 'Private island luxury with overwater villas, crystal turquoise lagoons, coral reef snorkeling, and romantic sunset cruises.',
    bestTimeToVisit: 'November to April',
    idealDuration: '5 Days / 4 Nights',
    highlights: ['Overwater Pool Villa Stay', 'Seaplane Scenic Flight', 'Manta Ray & Turtle Snorkeling', 'Candlelight Beach Dinner'],
  },
  {
    _id: 'dest-vietnam',
    _type: 'destination',
    name: 'Vietnam',
    slug: {_type: 'slug', current: 'vietnam'},
    country: 'Vietnam',
    region: 'Southeast Asia',
    shortDescription: 'Emerald waters of Halong Bay, lantern-lit alleys of Hoi An, French colonial Hanoi, and Golden Bridge in Ba Na Hills.',
    bestTimeToVisit: 'October to April',
    idealDuration: '7 Days / 6 Nights',
    highlights: ['Halong Bay Overnight Luxury Cruise', 'Da Nang Golden Hands Bridge', 'Hoi An Ancient Lantern Town', 'Hanoi Old Quarter'],
  },
  {
    _id: 'dest-srilanka',
    _type: 'destination',
    name: 'Sri Lanka',
    slug: {_type: 'slug', current: 'sri-lanka'},
    country: 'Sri Lanka',
    region: 'Indian Ocean',
    shortDescription: 'Misty tea plantations in Nuwara Eliya, golden beaches of Bentota, historic Sigiriya fortress, and coastal trains.',
    bestTimeToVisit: 'December to April',
    idealDuration: '6 Days / 5 Nights',
    highlights: ['Sigiriya Lion Rock Fortress', 'Scenic Kandy to Ella Train', 'Bentota Water Sports & Beach', 'Nuwara Eliya Tea Estate'],
  },
  {
    _id: 'dest-switzerland',
    _type: 'destination',
    name: 'Switzerland',
    slug: {_type: 'slug', current: 'switzerland'},
    country: 'Switzerland',
    region: 'Central Europe',
    shortDescription: 'The Top of Europe, pristine alpine lakes, scenic Swiss rail journeys, chocolate boutiques, and snow-dusted peaks.',
    bestTimeToVisit: 'May to October (Scenic) / Dec to March (Snow)',
    idealDuration: '7 Days / 6 Nights',
    highlights: ['Jungfraujoch Top of Europe', 'Mt. Titlis Revolving Cable Car', 'Lake Lucerne Scenic Cruise', 'Interlaken Alpine Valley'],
  },
  {
    _id: 'dest-japan',
    _type: 'destination',
    name: 'Japan',
    slug: {_type: 'slug', current: 'japan'},
    country: 'Japan',
    region: 'East Asia',
    shortDescription: 'Neon energy of Tokyo, majestic Mt. Fuji, centuries-old Kyoto Shinto shrines, and world-renowned Japanese culinary artistry.',
    bestTimeToVisit: 'March to May (Cherry Blossom) & Sept to Nov (Autumn Foliage)',
    idealDuration: '7 Days / 6 Nights',
    highlights: ['Tokyo Shibuya & Senso-ji', 'Mt. Fuji & Lake Kawaguchi', 'Kyoto Fushimi Inari Shrine', 'Shinkansen Bullet Train'],
  },
  {
    _id: 'dest-malaysia',
    _type: 'destination',
    name: 'Malaysia',
    slug: {_type: 'slug', current: 'malaysia'},
    country: 'Malaysia',
    region: 'Southeast Asia',
    shortDescription: 'Iconic Petronas Twin Towers, rainforest cable cars in Langkawi, colorful Batu Caves, and duty-free island beaches.',
    bestTimeToVisit: 'November to April',
    idealDuration: '5 Days / 4 Nights',
    highlights: ['Petronas Twin Towers Skybridge', 'Langkawi SkyCab & SkyBridge', 'Batu Caves Lord Murugan Temple', 'Langkawi Island Hopping'],
  },
]

// Import packages data from packagesData.ts
const packagesDataPath = path.join(__dirname, '../apps/web/src/lib/data/packagesData.ts')
const content = fs.readFileSync(packagesDataPath, 'utf8')

// We will construct the seed array
const seedDocs = [
  // 1. Site Settings
  {
    _id: 'siteSettings',
    _type: 'siteSettings',
    companyName: 'HappyFlying Tours & Travels LLP',
    tagline: 'Wings to wonder, journeys with heart, and travel crafted around you.',
    phone: '+91 9900113691',
    whatsapp: '919900113691',
    email: 'operations@happyflyingtravels.com',
    address: 'No 145, 3rd Floor, 80 Feet Road KHB Colony, 5th Block, Koramangala, Bangalore, Karnataka 560034',
    footerText: 'Where every journey takes wing with elegance, care, and unforgettable discovery. Headquartered in Koramangala, Bangalore.',
    socialLinks: [
      {_key: 'ig', platform: 'instagram', url: 'https://www.instagram.com/happyflying.in'},
      {_key: 'wa', platform: 'whatsapp', url: 'https://wa.me/919900113691'},
      {_key: 'yt', platform: 'youtube', url: 'https://youtube.com'}
    ],
    defaultSeo: {
      metaTitle: 'HappyFlying Tours & Travels | Luxury Tours & Bespoke Travel',
      metaDescription: 'Wings to wonder, journeys with heart, and bespoke holidays crafted around you by HappyFlying Tours & Travels Bangalore.',
      keywords: ['luxury travel', 'andaman tour packages', 'bangalore travel agency', 'bespoke holidays', 'honeymoon packages']
    },
    navigation: [
      {_key: 'nav-1', label: 'Home', href: '/'},
      {_key: 'nav-2', label: 'Packages', href: '/packages'},
      {_key: 'nav-3', label: 'Destinations', href: '/destinations'},
      {_key: 'nav-4', label: 'Services', href: '/services'},
      {_key: 'nav-5', label: 'About', href: '/about'},
      {_key: 'nav-6', label: 'Blog', href: '/blog'},
      {_key: 'nav-7', label: 'Travel Planner', href: '/travel-planner'},
      {_key: 'nav-8', label: 'Contact', href: '/contact'}
    ]
  },
  // 2. All 20 Destinations
  ...ALL_DESTINATIONS,
  // 3. Testimonials
  {_id: 'testimonial-1', _type: 'testimonial', name: 'Vikram & Sneha Rao', role: 'Honeymooners from Bangalore', rating: 5, comment: 'Our Andaman trip with HappyFlying was absolutely magical! From the private cruise booking on Makruzz to the hotel coordination in Havelock, everything was completely stress-free. 10/10 service!', featured: true},
  {_id: 'testimonial-2', _type: 'testimonial', name: 'Dr. Rajesh Kulkarni', role: 'Family Vacationer from Koramangala', rating: 5, comment: 'The on-ground team in Port Blair and Neil Island was prompt and courteous. Traveling with elderly parents was made very comfortable with dedicated AC cabs at every point. Highly recommended!', featured: true},
  {_id: 'testimonial-3', _type: 'testimonial', name: 'Ananya Sharma', role: 'Travel Enthusiast from Mumbai', rating: 5, comment: 'Radhanagar sunset and the snorkeling at Elephant beach were memories of a lifetime. HappyFlying took care of every ferry ticket and permit in advance. Outstanding experience!', featured: true},
  // 4. Services
  {_id: 'service-1', _type: 'service', title: 'Bespoke Holiday Packages', slug: {_type: 'slug', current: 'bespoke-holidays'}, shortDescription: 'Handcrafted domestic & international travel packages designed around your exact dates, style, and budget.', icon: 'globe', features: ['100% Tailored Day-by-Day Itineraries', 'Handpicked & Verified 4-Star & 5-Star Accommodations', 'Private Dedicated AC Cabs & Sightseeing', '24/7 On-Ground Concierge Assistance']},
  {_id: 'service-2', _type: 'service', title: 'Flight & Cruise Ticketing', slug: {_type: 'slug', current: 'flights-cruises'}, shortDescription: 'Competitive airfares, group flight bookings, and premium island cruise ticket reservations.', icon: 'plane', features: ['Domestic & International Airline Bookings', 'Instant Catamaran Cruise Holds (Makruzz / Nautika)', 'Special Group & Family Fare Discounts', 'Hassle-free Date Rescheduling Assistance']},
  // 5. Team
  {_id: 'team-1', _type: 'teamMember', name: 'Brijesh & Travel Concierge Team', role: 'Head of Travel Experiences', bio: '10+ years curating unforgettable bespoke journeys across Andaman, Kerala, Himachal, Bali, and Europe. Headquartered in Koramangala, Bangalore.', email: 'operations@happyflyingtravels.com', phone: '+91 9900113691'},
  // 6. Blog
  {_id: 'blog-1', _type: 'blogPost', title: 'Top 7 Things to Know Before Your First Andaman Island Trip', slug: {_type: 'slug', current: 'top-things-to-know-andaman'}, publishedAt: '2026-09-10T00:00:00.000Z', excerpt: 'Everything you need to know about ferry timings, island permits, water sports safety, and best seasons to visit the Andaman Islands.', categories: ['Andaman Travel', 'Travel Guide']}
]

// Add 20 Pricing Documents + 20 Packages
const packages = [
  // 10 Domestic
  {
    id: 'pkg-andaman-trip',
    title: 'Andaman Trip — Exotic 5D/4N Island Getaway',
    slug: 'andaman-trip',
    code: 'HF-AND-01',
    destId: 'dest-andaman',
    type: 'Domestic Tour',
    categories: ['Heritage & Nature', 'Family Holiday', 'Beach & Backwaters', 'Honeymoon & Luxury'],
    status: 'active',
    featured: true,
    duration: '4 N / 5 D',
    rating: 4.8,
    reviewCount: 48,
    summary: 'All-inclusive Andaman getaway featuring private AC vehicle on all islands, premium Makruzz/Nautika catamaran cruise tickets, Radhanagar sunset, Cellular Jail, and Elephant Beach snorkeling.',
    highlights: ['Private dedicated AC vehicle on all islands', 'Makruzz / Nautika premium catamaran tickets included', 'Elephant Beach coral snorkeling', 'Radhanagar Beach sunset', 'Cellular Jail entry & Light and Sound show', '4-Star hotels with daily breakfast & dinner'],
    inclusions: ['4-Star hotel accommodation on double sharing', 'Daily breakfast & dinner (MAP)', 'All catamaran ferry tickets on Makruzz/Nautika', 'All monument tickets, permits and private cab transfers'],
    exclusions: ['Lunch and unmentioned meals', 'Personal water sports add-ons', 'Airfare to Port Blair'],
    price: 24999,
    displayPrice: '₹24,999 / person'
  },
  {
    id: 'pkg-kashmir-paradise',
    title: 'Kashmir Paradise: Srinagar, Gulmarg & Pahalgam — 6D/5N',
    slug: 'kashmir-paradise-gulmarg-pahalgam',
    code: 'HF-KAS-02',
    destId: 'dest-kashmir',
    type: 'Domestic Tour',
    categories: ['Honeymoon & Luxury', 'Family Holiday', 'Heritage & Nature'],
    status: 'active',
    featured: true,
    duration: '5 N / 6 D',
    rating: 4.9,
    reviewCount: 36,
    summary: 'Experience paradise on Earth with a Dal Lake luxury houseboat stay, Gulmarg Gondola cable car ride, Betaab Valley in Pahalgam, and serene Mughal gardens.',
    highlights: ['1 Night in Luxury Dal Lake Deluxe Houseboat with Shikara sunset ride', 'Gulmarg Gondola Ride (Phase 1 & Phase 2 snow views)', 'Pahalgam excursion to Betaab Valley, Aru Valley & Chandanwari', 'Mughal Gardens of Srinagar', 'Private dedicated heating-equipped cab', 'Daily authentic Kashmiri Breakfast & Dinner'],
    inclusions: ['5 Nights accommodation (Houseboat + Hotels)', 'Daily breakfast and multi-course dinners', 'Private heating-equipped vehicle for all valley sightseeing', '1-Hour Shikara ride on Dal Lake'],
    exclusions: ['Gondola ride tickets and pony rides', 'Flight tickets to Srinagar'],
    price: 28499,
    displayPrice: '₹28,499 / person'
  },
  {
    id: 'pkg-kerala-backwaters',
    title: 'Kerala Serenity: Munnar Tea Hills, Thekkady & Alleppey Houseboat — 6D/5N',
    slug: 'kerala-munnar-alleppey-houseboat',
    code: 'HF-KER-03',
    destId: 'dest-kerala',
    type: 'Domestic Tour',
    categories: ['Honeymoon & Luxury', 'Beach & Backwaters', 'Family Holiday'],
    status: 'active',
    featured: true,
    duration: '5 N / 6 D',
    rating: 4.8,
    reviewCount: 52,
    summary: 'Drive through misty Munnar tea hills, spice plantations in Thekkady, and cruise the tranquil Alleppey backwaters on a private luxury houseboat.',
    highlights: ['Private Luxury AC Houseboat cruise in Alleppey with full traditional Kerala meals', '2 Nights in Munnar tea plantations', 'Thekkady spice plantation tour & Periyar boating', 'Fort Kochi heritage walk & Chinese nets', 'Private AC vehicle throughout'],
    inclusions: ['4 Nights hotels + 1 Night Private Houseboat with all meals onboard', 'Daily breakfast at hotels', 'Private dedicated AC vehicle from Kochi'],
    exclusions: ['Kathakali show / Elephant ride tickets', 'Airfare to Kochi'],
    price: 22999,
    displayPrice: '₹22,999 / person'
  },
  {
    id: 'pkg-golden-triangle',
    title: 'Royal Golden Triangle: Delhi, Agra Taj Mahal & Jaipur — 6D/5N',
    slug: 'golden-triangle-delhi-agra-jaipur',
    code: 'HF-GLD-04',
    destId: 'dest-rajasthan',
    type: 'Domestic Tour',
    categories: ['Heritage & Nature', 'Family Holiday'],
    status: 'active',
    featured: false,
    duration: '5 N / 6 D',
    rating: 4.7,
    reviewCount: 41,
    summary: 'The definitive Indian cultural trail. Marvel at sunrise over the Taj Mahal in Agra, explore Jaipur\'s Amber Fort and City Palace, and uncover Delhi monuments.',
    highlights: ['Sunrise tour of the Taj Mahal in Agra', 'Jaipur Amber Fort, Hawa Mahal & City Palace', 'Agra Fort & Fatehpur Sikri UNESCO tours', 'Delhi Qutub Minar & India Gate', 'Chauffeur-driven private AC Sedan'],
    inclusions: ['5 Nights 4-Star luxury heritage hotel accommodation', 'Daily buffet breakfast at all hotels', 'Private AC vehicle with toll and interstate taxes included'],
    exclusions: ['Monument entrance fees', 'Airfare/Train tickets'],
    price: 21499,
    displayPrice: '₹21,499 / person'
  },
  {
    id: 'pkg-goa-luxury-escape',
    title: 'Goa Luxury Coastal Escape & Private Yacht Cruise — 4D/3N',
    slug: 'goa-luxury-beach-yacht-escape',
    code: 'HF-GOA-05',
    destId: 'dest-goa',
    type: 'Domestic Tour',
    categories: ['Beach & Backwaters', 'Honeymoon & Luxury', 'Family Holiday'],
    status: 'active',
    featured: false,
    duration: '3 N / 4 D',
    rating: 4.8,
    reviewCount: 29,
    summary: 'Stay at a 5-star beachfront resort, cruise the Arabian Sea on a private yacht, and explore North and South Goa’s scenic coastal treasures.',
    highlights: ['2-Hour Private Sunset Yacht Charter with drinks along Mandovi River', '5-Star Beachfront Luxury Resort stay', 'Private AC vehicle for North & South Goa beach trails', 'VIP table reservations at oceanfront beach clubs'],
    inclusions: ['3 Nights in 5-star resort with daily luxury breakfast', 'Private Yacht charter for 2 hours with crew', 'Airport transfers in private AC vehicle'],
    exclusions: ['Flight tickets', 'Water sports gear fees'],
    price: 19999,
    displayPrice: '₹19,999 / person'
  },
  {
    id: 'pkg-himachal-manali',
    title: 'Himachal Scenic Grandeur: Manali, Solang Valley & Shimla — 6D/5N',
    slug: 'himachal-manali-solang-shimla',
    code: 'HF-HIM-06',
    destId: 'dest-himachal',
    type: 'Domestic Tour',
    categories: ['Heritage & Nature', 'Family Holiday', 'Adventure'],
    status: 'active',
    featured: false,
    duration: '5 N / 6 D',
    rating: 4.7,
    reviewCount: 38,
    summary: 'Himalayan road trips through pine-covered slopes, Atal Tunnel, Solang Valley adventure sports, and the colonial charm of Shimla\'s Ridge.',
    highlights: ['Solang Valley adventure hub (Paragliding, Zorbing & snow sports)', 'Atal Tunnel drive to Sissu, Lahaul Valley', 'Old Manali cafes and Hadimba Temple', 'Shimla Mall Road, The Ridge & Kufri', 'Private dedicated vehicle for the full circuit'],
    inclusions: ['5 Nights hotel stay with daily breakfast and dinner (MAP)', 'Exclusive private AC/Heated vehicle for complete mountain touring'],
    exclusions: ['Activity charges at Solang/Kufri', 'Rohtang Pass permit fee'],
    price: 20499,
    displayPrice: '₹20,499 / person'
  },
  {
    id: 'pkg-ladakh-pangong',
    title: 'Ladakh High Passes, Nubra Sand Dunes & Pangong Tso — 7D/6N',
    slug: 'ladakh-pangong-nubra-valley',
    code: 'HF-LAD-07',
    destId: 'dest-ladakh',
    type: 'Domestic Tour',
    categories: ['Adventure', 'Heritage & Nature', 'Honeymoon & Luxury'],
    status: 'active',
    featured: true,
    duration: '6 N / 7 D',
    rating: 4.9,
    reviewCount: 44,
    summary: 'Cross Khardung La (17,982 ft), camp under star-studded skies at Pangong Tso Lake, and ride double-humped camels in Nubra Valley.',
    highlights: ['1 Night luxury dome camping on the banks of Pangong Tso Lake', 'Drive across Khardung La & Chang La mountain passes', 'Nubra Valley Hunder white sand dunes & Bactrian camel safari', 'Leh Palace, Shanti Stupa, and Magnetic Hill', 'Oxygen-cylinder equipped private vehicle with local driver'],
    inclusions: ['6 Nights accommodation with daily breakfast and hot dinner', 'All Ladakh Inner Line Permits and environmental fees', 'Oxygen cylinder support in vehicle'],
    exclusions: ['Airfare to Leh', 'Camel ride charges'],
    price: 32999,
    displayPrice: '₹32,999 / person'
  },
  {
    id: 'pkg-spiritual-uttarakhand',
    title: 'Spiritual Uttarakhand: Rishikesh, Haridwar & Mussoorie — 6D/5N',
    slug: 'spiritual-uttarakhand-rishikesh-mussoorie',
    code: 'HF-UTT-08',
    destId: 'dest-uttarakhand',
    type: 'Domestic Tour',
    categories: ['Heritage & Nature', 'Family Holiday'],
    status: 'active',
    featured: false,
    duration: '5 N / 6 D',
    rating: 4.8,
    reviewCount: 31,
    summary: 'Experience the magical evening Ganga Aarti in Rishikesh & Haridwar, thrilling white-water rafting, and the colonial charm of Mussoorie.',
    highlights: ['VIP front-row seating for Triveni Ghat Ganga Aarti in Rishikesh', 'Ganges River Rafting & cliff jumping session', 'Mussoorie Queen of Hills: Kempty Falls & Mall Road', 'Haridwar Har Ki Pauri holy dip & Mansa Devi ropeway', 'Private dedicated AC vehicle throughout'],
    inclusions: ['5 Nights hotel stay with daily breakfast and dinner', 'Private AC vehicle for all transfers and tours', 'River rafting gear and certified river guide session'],
    exclusions: ['Ropeway cable car tickets', 'Airfare/Train tickets'],
    price: 18999,
    displayPrice: '₹18,999 / person'
  },
  {
    id: 'pkg-sikkim-darjeeling',
    title: 'Sikkim & Darjeeling: Himalayan Tea Hills & Glacial Lakes — 6D/5N',
    slug: 'sikkim-gangtok-darjeeling-himalaya',
    code: 'HF-SIK-09',
    destId: 'dest-sikkim',
    type: 'Domestic Tour',
    categories: ['Heritage & Nature', 'Family Holiday', 'Honeymoon & Luxury'],
    status: 'active',
    featured: false,
    duration: '5 N / 6 D',
    rating: 4.8,
    reviewCount: 27,
    summary: 'Gaze at the snow peaks of Mt. Kanchenjunga from Tiger Hill, ride the heritage Darjeeling Toy Train, and journey to the glacial heights of Tsomgo Lake in Sikkim.',
    highlights: ['Tiger Hill sunrise over Mt. Kanchenjunga', 'High-altitude glacial Tsomgo Lake & Baba Mandir excursion', 'Darjeeling Himalayan Railway (UNESCO Toy Train) ride', 'Organic Darjeeling tea estate tasting tour', 'Gangtok MG Marg & Rumtek Monastery'],
    inclusions: ['5 Nights in 4-star boutique Himalayan hotels', 'Daily breakfast and dinner (MAP)', 'Private vehicle for Bagdogra pickup, drop, and mountain touring', 'Sikkim Protected Area Permits for Tsomgo Lake'],
    exclusions: ['Nathula Pass Indo-China border permit add-on', 'Toy train joyride charges'],
    price: 24499,
    displayPrice: '₹24,499 / person'
  },
  {
    id: 'pkg-royal-rajasthan-udaipur',
    title: 'Royal Rajasthan: Udaipur Lake City & Jodhpur Blue Grandeur — 5D/4N',
    slug: 'royal-udaipur-jodhpur-palace-trail',
    code: 'HF-RAJ-10',
    destId: 'dest-udaipur',
    type: 'Domestic Tour',
    categories: ['Honeymoon & Luxury', 'Heritage & Nature'],
    status: 'active',
    featured: false,
    duration: '4 N / 5 D',
    rating: 4.9,
    reviewCount: 33,
    summary: 'Sunset boat cruises on Lake Pichola in Udaipur, magnificent marble City Palaces, and the towering cliffside Mehrangarh Fort in Jodhpur.',
    highlights: ['Sunset boat cruise on Lake Pichola with views of Lake Palace', 'Guided tour of Udaipur City Palace & Saheliyon Ki Bari', 'Ranakpur Jain Temple 1,444 marble pillars visit', 'Jodhpur Mehrangarh Fort & Jaswant Thada', 'Private heritage luxury AC Sedan with chauffeur'],
    inclusions: ['4 Nights in luxury heritage Haveli/Palace hotels', 'Daily royal breakfast', 'Lake Pichola private boat ride voucher', 'All intercity transfers in private AC vehicle'],
    exclusions: ['Monument entrance fees', 'Airfare to Udaipur/Jodhpur'],
    price: 23999,
    displayPrice: '₹23,999 / person'
  },

  // 10 International
  {
    id: 'pkg-bali-tropical-ubud',
    title: 'Bali Island Fantasy: Ubud Culture, Nusa Penida & Beach Resorts — 6D/5N',
    slug: 'bali-tropical-ubud-nusa-penida',
    code: 'HF-BALI-01',
    destId: 'dest-bali',
    type: 'International Tour',
    categories: ['Honeymoon & Luxury', 'Beach & Backwaters', 'Family Holiday'],
    status: 'active',
    featured: true,
    duration: '5 N / 6 D',
    rating: 4.9,
    reviewCount: 64,
    summary: 'Relax in a private pool villa, swing over the emerald Ubud rice terraces, take a speedboat to Nusa Penida\'s T-Rex cliff, and watch Tanah Lot sunset.',
    highlights: ['Full-Day Nusa Penida Speedboat Tour: Kelingking Beach & Broken Beach', '2 Nights in Private Pool Villa with floating breakfast', 'Ubud Bali Jungle Swing & Tegalalang Rice Terraces', 'Tanah Lot sunset & Uluwatu Kecak Fire Dance', 'Private chauffeur-driven car for all tours', 'Balinese Spa massage session included'],
    inclusions: ['5 Nights luxury stay (Seminyak + Ubud Pool Villa)', 'Daily breakfast + 1 Floating Pool Breakfast', 'Speedboat transfers to Nusa Penida with island cab & lunch', 'All airport pickup, drop, and day tours'],
    exclusions: ['International airfare to DPS', 'Visa on Arrival fee'],
    price: 38999,
    displayPrice: '₹38,999 / person'
  },
  {
    id: 'pkg-dubai-skylines',
    title: 'Dubai Extravaganza: Burj Khalifa, Desert Safari & Luxury Yacht — 5D/4N',
    slug: 'dubai-skylines-desert-safari-luxury',
    code: 'HF-DXB-02',
    destId: 'dest-dubai',
    type: 'International Tour',
    categories: ['Honeymoon & Luxury', 'Family Holiday'],
    status: 'active',
    featured: true,
    duration: '4 N / 5 D',
    rating: 4.9,
    reviewCount: 58,
    summary: 'Stand at the top of Burj Khalifa, experience thrilling dune bashing in a 4x4 Land Cruiser, and sail on a luxury Dubai Marina yacht.',
    highlights: ['Burj Khalifa 124th & 125th Floor Observation Deck Tickets', 'Premium Desert Safari with 4x4 Dune Bashing & BBQ Buffet', '2-Hour Dubai Marina Luxury Yacht Cruise', 'Museum of the Future & Dubai Frame visit', 'Dubai Miracle Garden & Global Village evening tour', 'Private luxury AC transfers throughout'],
    inclusions: ['4 Nights in 4-Star/5-Star Dubai hotel', 'Daily international buffet breakfast', 'Desert Safari with VIP BBQ dinner and shows', 'Burj Khalifa and Marina Yacht tickets'],
    exclusions: ['Flight tickets to Dubai', 'Tourism Dirham fee paid directly at hotel'],
    price: 42999,
    displayPrice: '₹42,999 / person'
  },
  {
    id: 'pkg-thailand-phuket-bangkok',
    title: 'Thailand Dual Wonders: Phuket Beaches & Bangkok City Lights — 6D/5N',
    slug: 'thailand-phuket-bangkok-island-hopping',
    code: 'HF-THAI-03',
    destId: 'dest-thailand',
    type: 'International Tour',
    categories: ['Beach & Backwaters', 'Family Holiday', 'Honeymoon & Luxury'],
    status: 'active',
    featured: true,
    duration: '5 N / 6 D',
    rating: 4.8,
    reviewCount: 49,
    summary: 'Speedboat cruise to Phi Phi & Maya Bay, relax on Patong beach, and enjoy Chao Phraya luxury dinner cruises in Bangkok.',
    highlights: ['Phi Phi Islands & Maya Bay luxury speedboat tour with buffet lunch & snorkeling', 'Phuket Big Buddha & Promthep Cape sunset view', 'Chao Phraya Princess luxury dinner cruise in Bangkok', 'Bangkok City & Golden Buddha Temple Tour', 'Private airport and inter-hotel AC transfers'],
    inclusions: ['3 Nights Phuket resort + 2 Nights Bangkok city hotel', 'Daily buffet breakfast', 'Phi Phi island speedboat tour with national park fees and lunch', 'Chao Phraya dinner cruise ticket', 'All private airport transfers'],
    exclusions: ['International & internal domestic flights', 'Personal expenses'],
    price: 29999,
    displayPrice: '₹29,999 / person'
  },
  {
    id: 'pkg-singapore-sentosa',
    title: 'Singapore Sparkle: Marina Bay, Sentosa & Universal Studios — 5D/4N',
    slug: 'singapore-sentosa-universal-studios',
    code: 'HF-SIN-04',
    destId: 'dest-singapore',
    type: 'International Tour',
    categories: ['Family Holiday', 'Honeymoon & Luxury'],
    status: 'active',
    featured: false,
    duration: '4 N / 5 D',
    rating: 4.9,
    reviewCount: 42,
    summary: 'Universal Studios on Sentosa Island, Gardens by the Bay Supertrees, and the world-first Night Safari.',
    highlights: ['One-day full access pass to Universal Studios Singapore', 'Gardens by the Bay: Flower Dome & Cloud Forest', 'Singapore Night Safari with tram ride', 'Marina Bay Sands SkyPark Observation Deck', 'Mount Faber to Sentosa cable car network ride'],
    inclusions: ['4 Nights in 4-Star Singapore hotel', 'Daily international breakfast', 'All major attraction entry passes', 'Private airport transfers from Changi'],
    exclusions: ['Flight tickets to Singapore', 'Visa processing fee'],
    price: 47999,
    displayPrice: '₹47,999 / person'
  },
  {
    id: 'pkg-maldives-overwater',
    title: 'Maldives Paradise: 5-Star Overwater Pool Villa Luxury Escape — 5D/4N',
    slug: 'maldives-overwater-villa-luxury-escape',
    code: 'HF-MLD-05',
    destId: 'dest-maldives',
    type: 'International Tour',
    categories: ['Honeymoon & Luxury', 'Beach & Backwaters'],
    status: 'active',
    featured: true,
    duration: '4 N / 5 D',
    rating: 5.0,
    reviewCount: 39,
    summary: 'Private overwater villa with plunge pool, turquoise coral lagoon, all-inclusive gourmet dining, and sunset dolphin cruise.',
    highlights: ['5-Star Luxury Overwater Villa with private plunge pool and lagoon ladder', 'All-Inclusive Dine-Around Meal Plan (Breakfast, Lunch, Dinner & Drinks)', 'Scenic Speedboat / Seaplane airport transfers', 'Complimentary non-motorized water sports (Kayaking, Snorkeling)', 'Romantic sunset dolphin cruise on traditional Dhoni boat'],
    inclusions: ['4 Nights in Overwater Villa on private island resort', 'All Inclusive meals and beverages plan', 'Round-trip airport speedboat or seaplane transfers', 'All Maldivian Green Tax included'],
    exclusions: ['International flights to Male (MLE)', 'Scuba diving certification courses'],
    price: 84999,
    displayPrice: '₹84,999 / person'
  },
  {
    id: 'pkg-vietnam-halong-bay',
    title: 'Vietnam Jewels: Hanoi, Halong Bay 5-Star Cruise & Da Nang — 7D/6N',
    slug: 'vietnam-halong-bay-hanoi-da-nang',
    code: 'HF-VIE-06',
    destId: 'dest-vietnam',
    type: 'International Tour',
    categories: ['Heritage & Nature', 'Honeymoon & Luxury', 'Family Holiday'],
    status: 'active',
    featured: false,
    duration: '6 N / 7 D',
    rating: 4.8,
    reviewCount: 35,
    summary: 'Sail overnight amidst Halong Bay\'s limestone pillars, walk the Golden Hands Bridge in Da Nang, and explore lantern-lit Hoi An.',
    highlights: ['2D/1N Overnight Luxury Cruise in Halong Bay with kayaking & squid fishing', 'Ba Na Hills cable car ride & Golden Hands Bridge walk', 'Hoi An Ancient Lantern Town walking tour & lantern boat ride', 'Hanoi Old Quarter Rickshaw tour and Train Street', 'Private English-speaking guides and AC transfers throughout'],
    inclusions: ['5 Nights hotels + 1 Night 5-Star Halong Bay Cruise', 'Daily breakfast + Full board meals on Halong cruise + Tour lunches', 'All entrance fees and cable car passes to Ba Na Hills'],
    exclusions: ['International flights', 'Vietnam E-visa fee'],
    price: 46999,
    displayPrice: '₹46,999 / person'
  },
  {
    id: 'pkg-sri-lanka-tea-trails',
    title: 'Sri Lanka Wonders: Ramayana Trail, Nuwara Eliya & Bentota — 6D/5N',
    slug: 'sri-lanka-tea-gardens-bentota-beaches',
    code: 'HF-SRI-07',
    destId: 'dest-srilanka',
    type: 'International Tour',
    categories: ['Heritage & Nature', 'Beach & Backwaters', 'Family Holiday'],
    status: 'active',
    featured: false,
    duration: '5 N / 6 D',
    rating: 4.8,
    reviewCount: 28,
    summary: 'Climb the ancient Sigiriya Lion Rock, wander aromatic tea estates in Little England Nuwara Eliya, and relax on Bentota’s beaches.',
    highlights: ['UNESCO World Heritage Sigiriya Rock Fortress climb', 'Temple of the Sacred Tooth Relic in Kandy', 'Highland tea plantation tour & Ceylon tea tasting in Nuwara Eliya', 'Bentota beach leisure & Madu Ganga mangrove boat safari', 'Private dedicated AC vehicle with English-speaking chauffeur guide'],
    inclusions: ['5 Nights in luxury 4-star resorts with daily breakfast and dinner (MAP)', 'Madu river boat safari tickets and spice garden tours', 'All airport pickup, drop, and intercity touring'],
    exclusions: ['Flight tickets to Colombo', 'Sri Lanka ETA Visa'],
    price: 27999,
    displayPrice: '₹27,999 / person'
  },
  {
    id: 'pkg-switzerland-alpine',
    title: 'Switzerland Alpine Grandeur: Zurich, Interlaken & Lucerne — 7D/6N',
    slug: 'switzerland-alpine-dream-interlaken-lucerne',
    code: 'HF-SWISS-08',
    destId: 'dest-switzerland',
    type: 'International Tour',
    categories: ['Honeymoon & Luxury', 'Heritage & Nature', 'Family Holiday'],
    status: 'active',
    featured: true,
    duration: '6 N / 7 D',
    rating: 5.0,
    reviewCount: 37,
    summary: 'Ascend to Jungfraujoch — the Top of Europe, ride Mt. Titlis revolving cable cars, cruise Lake Lucerne, and travel on Swiss scenic trains.',
    highlights: ['Excursion to Jungfraujoch Top of Europe with Sphinx Observatory', 'Mount Titlis Rotair revolving cable car & Cliff Walk bridge', 'Steamboat cruise across Lake Lucerne to Chapel Bridge', '8-Day Swiss Travel Pass for unlimited scenic trains and boats', 'Central hotel stays in Zurich, Lucerne, and Interlaken'],
    inclusions: ['6 Nights in 4-Star Swiss hospitality hotels', 'Daily Swiss buffet breakfast', 'Swiss Travel Pass (Consecutive) in 2nd Class', 'Mountain excursion vouchers to Mt. Titlis and Jungfraujoch'],
    exclusions: ['Schengen Visa fee', 'International flights to Zurich'],
    price: 124999,
    displayPrice: '₹1,24,999 / person'
  },
  {
    id: 'pkg-japan-tokyo-kyoto',
    title: 'Japan Blossom & Imperial Heritage: Tokyo, Mt. Fuji & Kyoto — 7D/6N',
    slug: 'japan-tokyo-kyoto-mount-fuji-heritage',
    code: 'HF-JPN-09',
    destId: 'dest-japan',
    type: 'International Tour',
    categories: ['Heritage & Nature', 'Family Holiday', 'Honeymoon & Luxury'],
    status: 'active',
    featured: false,
    duration: '6 N / 7 D',
    rating: 4.9,
    reviewCount: 26,
    summary: 'Ride the Shinkansen Bullet Train, stand before iconic Mt. Fuji, wander thousands of vermillion torii gates at Fushimi Inari, and shop in Tokyo.',
    highlights: ['Shinkansen Bullet Train experience between Tokyo and Kyoto', 'Mt. Fuji 5th Station & Lake Ashi pirate boat cruise in Hakone', 'Kyoto Fushimi Inari Shrine, Golden Pavilion & Arashiyama Bamboo', 'Tokyo Shibuya Crossing, teamLab Planets digital art & Senso-ji', '7-day JR rail pass convenience and private tour excursions'],
    inclusions: ['6 Nights in 4-star centrally located hotels in Tokyo and Kyoto', 'Daily Japanese/Western breakfast', 'Bullet train tickets + Mt. Fuji full-day tour with lunch', 'Private airport transfers in Tokyo and Osaka'],
    exclusions: ['Japan Visa fees', 'International airfare to Tokyo'],
    price: 139999,
    displayPrice: '₹1,39,999 / person'
  },
  {
    id: 'pkg-malaysia-twin-wonders',
    title: 'Malaysia Duo: Kuala Lumpur Skyline & Langkawi Island Beach — 5D/4N',
    slug: 'malaysia-kuala-lumpur-langkawi-island',
    code: 'HF-MYS-10',
    destId: 'dest-malaysia',
    type: 'International Tour',
    categories: ['Beach & Backwaters', 'Family Holiday', 'Honeymoon & Luxury'],
    status: 'active',
    featured: false,
    duration: '4 N / 5 D',
    rating: 4.8,
    reviewCount: 30,
    summary: 'Gaze at the Petronas Twin Towers in KL, take the Langkawi Cable Car over ancient rainforests, and island hop around turquoise beaches.',
    highlights: ['Petronas Twin Towers observation deck & skybridge visit', 'Langkawi SkyCab & world\'s steepest SkyBridge over rainforests', 'Full-Day Langkawi Island Hopping tour with eagle feeding', 'Batu Caves rainbow steps & giant golden statue in Kuala Lumpur', 'Private air-conditioned transfers for all tours'],
    inclusions: ['2 Nights KL hotel + 2 Nights Langkawi beachfront resort', 'Daily international buffet breakfast', 'Langkawi Island hopping boat tour & SkyCab passes', 'All private airport and inter-hotel transfers'],
    exclusions: ['International & domestic airfares', 'Malaysia Tourism Tax'],
    price: 28999,
    displayPrice: '₹28,999 / person'
  }
]

packages.forEach((pkg, index) => {
  const pricingId = `pricing-${pkg.slug}`
  // 1. Pricing Document
  seedDocs.push({
    _id: pricingId,
    _type: 'pricing',
    title: `${pkg.title} - Active Plan`,
    validFrom: '2026-01-01',
    validTo: '2026-12-31',
    occupancy: 'Double Sharing',
    adults: 2,
    children: 0,
    rooms: 1,
    mealPlan: 'Standard Meal Plan (as specified in package)',
    basePrice: pkg.price,
    taxes: 0,
    markup: 0,
    finalPrice: pkg.price,
    displayPrice: pkg.displayPrice,
    currency: 'INR',
    notes: 'Rates are on double sharing basis with vehicle and sightseeing inclusions.'
  })

  // 2. Package Document
  seedDocs.push({
    _id: pkg.id,
    _type: 'travelPackage',
    title: pkg.title,
    slug: {_type: 'slug', current: pkg.slug},
    packageCode: pkg.code,
    destination: {_type: 'reference', _ref: pkg.destId},
    packageType: pkg.type,
    categories: pkg.categories,
    status: pkg.status,
    featured: pkg.featured,
    duration: pkg.duration,
    rating: pkg.rating,
    reviewCount: pkg.reviewCount,
    summary: pkg.summary,
    highlights: pkg.highlights,
    inclusions: pkg.inclusions,
    exclusions: pkg.exclusions,
    importantNotes: [
      'Carry valid government-issued photo identification at all times.',
      'Sightseeing schedules are subject to local weather and traffic conditions.',
      'Hotels maintain standard check-in at 12:00 PM / 2:00 PM and check-out at 10:00 AM / 11:00 AM.'
    ],
    cancellationPolicy: [
      '30+ days prior to departure: 15% cancellation fee.',
      '15 to 29 days prior to departure: 50% cancellation fee.',
      'Less than 15 days prior to departure: 100% cancellation fee.'
    ],
    pricing: {_type: 'reference', _ref: pricingId},
    bookingCta: {
      title: `Book & Customise ${pkg.title}`,
      description: 'Speak directly with our Bangalore travel concierges for instant seat holds, custom dates, or group discounts.',
      phone: '+91 9900113691',
      whatsapp: '919900113691',
      email: 'operations@happyflyingtravels.com',
      buttonText: 'Inquire on WhatsApp'
    },
    seo: {
      metaTitle: `${pkg.title} — HappyFlying Tours & Travels`,
      metaDescription: pkg.summary
    }
  })
})

const ndjsonLines = seedDocs.map(doc => JSON.stringify(doc)).join('\n') + '\n'
const outputPath = path.join(__dirname, '../apps/studio/seed-data.ndjson')
fs.writeFileSync(outputPath, ndjsonLines, 'utf8')
console.log(`Successfully generated ${seedDocs.length} documents in ${outputPath}`)
